name: dental-backend
channels:
  - conda-forge
  - open3d-admin
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.20.0
    - python-multipart>=0.0.6
    - trimesh[easy]>=3.15.0
    - pygltflib>=1.15.0
    - pillow>=9.0.0
  - open3d
