name: dental-backend
channels:
  - conda-forge
  - open3d-admin
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.20.0
    - python-multipart>=0.0.6
  - open3d
